// <auto-generated />
namespace GeneralStoreAPI_New.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GeneralStoreAPI_NewModelsProductDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GeneralStoreAPI_NewModelsProductDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202101231248088_GeneralStoreAPI_New.Models.ProductDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
